### ISSUE TITLE
installation successful, but initialization fails

### ISSUE THREAD

**Issue by rbehrouzi** [cryoem-uoft/cryosparc-issues#123]
While trying to install on our main gpu workstation (scientific linux 7.2), the installation completed, but initialization failed at GPU step. I have used this system for other packages that use cuda. 
Here is the message:
```
--------------------- GPUs -----------------------------------------

  CryoSPARC includes a scheduler and queuing system for jobs. This
  can be configured to run on only some of the GPUs in your system,
  in case you want to reserve some for other uses.

  Right now, all GPUs will be enabled...
Traceback (most recent call last):
  File "/RAID10/cryosparc-beta/bin/configure.py", line 337, in <module>
    import pycuda.driver as cudrv
  File "/RAID10/cryosparc-beta/anaconda2/lib/python2.7/site-packages/pycuda/driver.py", line 5, in <module>
    from pycuda._driver import *  # noqa
ImportError: libcurand.so.7.5: cannot open shared object file: No such file or directory
 ERROR:


Traceback (most recent call last):
  File "/RAID10/cryosparc-beta/bin/configure.py", line 141, in <module>
    trycall(["cryosparc", "configure", "gpu", "enable", "all"])
  File "/RAID10/cryosparc-beta/bin/configure.py", line 23, in trycall
    ret = subprocess.check_output(cmds, **kwargs)
  File "/RAID10/cryosparc-beta/anaconda2/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['cryosparc', 'configure', 'gpu', 'enable', 'all']' returned non-zero exit status 1

```
PS: I tried installation on a local ubuntu 16.04 which completed and initialized successfully.

**Comment by alipunjani** [comment]
Hi Reza,

Thanks for logging this issue! 
I think the problem is the following:
The cryosparc installer looks for `nvcc` in the path. If it is found (as it was on your scientific linux 7.2 machine) then the installer assumes that _both_ `cuda/bin` is in the PATH and `cuda/lib64` is in the LD_LIBRARY_PATH. In your case, `cuda/lib64` was not in LD_LIBRARY_PATH, because that's where libcurand.so lives. If cuda is at `/usr/local/cuda`, the simple solution is to add

`LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH`

to your `~/.bashrc`. Then you can remove cryosparc and install it again and everything should be fine. If you've already started using cryoSPARC on your Ubuntu machine then you'll probably have to contact us at register@cryosparc.com to switch the installation to the other machine.

Hope that helps,
Ali

**Comment by biochemical** [comment]
Hi Ali.
Thanks a lot for the help. I'll look into this and as soon as I make sure I can run the version on this workstation, I'll get in touch to transfer the license.
