### ISSUE TITLE
Installer fails during "All GPUs will be enabled" step

### ISSUE THREAD

**Issue by lu-anaphase** [cryoem-uoft/cryosparc-issues#187]
Dear cryoSPARC team,

My installation fails midway because the installer is looking for CUDA 7.5 even though I have 8.0 installed. Is there a way to force the usage of CUDA 8.0? This doesn't seem to be related to Jian's previously reported CUDA version-confusion error, which only manifested after a completed installation.

EDIT: This machine previously had CUDA 7.5 installed, but I completely removed 7.5 and associated drivers before install 8.0. The command 'nvcc -V' correctly reports 8.0 as the CUDA version.

My machine info:
Ubuntu 14.04.5 LTS
CUDA 8.0 (installed at /usr/local)
nvcc: V8.0.61
NVIDIA driver: 375.39
GPUs: GTX 1070

Here's the error:
```
  Right now, all GPUs will be enabled...
Traceback (most recent call last):
  File "/EM/cryosparc/bin/configure.py", line 331, in <module>
    import pycuda.driver as cudrv
  File "/EM/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/driver.py", line 5, in <module>
    from pycuda._driver import *  # noqa
ImportError: libcurand.so.7.5: cannot open shared object file: No such file or directory
 ERROR:


Traceback (most recent call last):
  File "/EM/cryosparc/bin/configure.py", line 128, in <module>
    trycall(["cryosparc", "configure", "gpu", "enable", "all"])
  File "/EM/cryosparc/bin/util.py", line 8, in trycall
    ret = subprocess.check_output(cmds, **kwargs)
  File "/EM/cryosparc/anaconda2/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['cryosparc', 'configure', 'gpu', 'enable', 'all']' returned non-zero exit status 1
```

**Comment by AndyPurk** [comment]
I've also just come across this issue and have failed to find a quick fix. Had both versions 7.5 and 8.0 of CUDA installed, but cards gave the reported error during the same step. 
The GPU card is a GTX 1080 and as I previously reported will only run with CUDA 8.0 (sm_61 required).

**Comment by suhaildawood** [comment]
Hi,

The discussion in these pervious issues might be helpful:
https://github.com/cryoem-uoft/cryosparc-issues/issues/130
https://github.com/cryoem-uoft/cryosparc-issues/issues/71

**Comment by AndyPurk** [comment]
Unfortunately not, a completely fresh install of Cryosparc still picks up the libcurand.so.7.5, rather than the libcurand.so.8.0. The CUDA 8.0 paths are correctly detected by the installer otherwise. Issue #132 was my report of the initial problems with the sm_61 issue and was resolved with an earlier version.

**Comment by AndyPurk** [comment]
OK, I started from scratch, with a new bash session and removing the Cryosparc configuration saved in .bashrc.

Installed against CUDA 7.5 and then followed the instructions in #132 to switch to CUDA 8.0. Not sure if this will help the original poster. This seems to have worked, maybe because LD_LIBRARY_PATH was now correctly set in the shell.

**Comment by lu-anaphase** [comment]
Dear suhaildawood & AndyPurk,

Thanks for your advice and comments. Unfortunately I get the same error message even though I have completely wiped both cuda 7.5 and 8.0, including all the install files, reinstalled cuda 8.0, manually inserted the PATH and LD_LIBRARY_PATH lines in my .bashrc to point explicitly to the /usr/local/cuda-8.0 directories, then verified these correct paths with the echo command.

It's as if the cryosparc installer is downloading install files that explicitly point to cuda 7.5. I'd rather not  install cryosparc in a cuda 7.5 system, then upgrade to cuda 8.0, which according to AndyPurk is the only fix for this issue.

Is there a way to force the cryosparc installer to look at a generic "cuda" symlink instead of an explicity path? Or is the installer somehow pairing cuda 7.5 to my license?

Thanks.
Lu

**Comment by alipunjani** [comment]
Hi Lu,

Sorry for this trouble, it does seem very confusing. The cryoSPARC installer should not have any CUDA 7.5 specific parts, or any kind of pairing with licenses.

I believe what's happening is that when you first installed cryoSPARC with CUDA7.5, the cryoSPARC installer compiled and installed pyCUDA (a python package) against CUDA7.5. When you install cryoSPARC later with CUDA8.0, everything should have worked fine, except that pyCUDA gets installed *from a local cache* instead of being re-compiled against CUDA8.0 even though CUDA7.5 is not in the system.

Can you try clearing the pip cache:
`rm -rf ~/.cache/pip`
then installing again? This should hopefully work. I've also changed the cryoSPARC installer to force pip to not use the cache for pycuda.

Please let us know if that works.
Ali

**Comment by lu-anaphase** [comment]
Hi Ali,

Your fix worked perfectly. Furthermore, I was able to install cryosparc without first having the CUDA 8.0 PATH and LD_LIBRARY_PATH lines in my .bashrc.

BTW, I didn't even know the pip cache hidden directory existed until now. 

Thanks.
Lu

**Comment by alipunjani** [comment]
Great :) Yes I didn't know about the hidden cache until this morning either!
