### ISSUE TITLE
Checking uniqueness of files in SSD caching

### ISSUE THREAD

**Issue by johnrubinstein** [cryoem-uoft/cryosparc-issues#88]
Okay, this is a hard one to describe and I'm not exactly sure I know what happened but I have a theory:
1) I created particle stacks that were bad (how they were bad isn't really relevant, these ones had been mis-picked with the last 2/3 of the particles selected from coordinates that didn't correspond to particles - from a version of alignparts.py I'm working on)
2) I copied to the GPU machine and created a dataset in cryoSPARC
3) I did 3D classification and refinement and got a bad result
4) I realized my problem with particle picking and fixed it
5) [*here's my mistake I think*] I copied the good particles to the same directory on the GPU machine as the bad ones, overwriting the bad particles
6) I remade the dataset in cryoSPARC
7) I re-did the 3-D classification and refinement and *still* got a bad result
8) I spent 3 days trying to figure out what the bug was in alignparts
9) Finally created a new directory on HHD, remade a new dataset, re-did 3D classification and refinement (all with the same data) and it worked.

What I think happened here is that, due to SSD caching, in steps 6-7 I was actually working with the same bad particles that I was in steps 1-3. If this is the case, how does cryoSPARC decide if the files it needs are already cached? Could it use md5sum or an equivalent to see if files on the SSD really are the same as the ones on the HDD? My mistake may not be as rare as it sounds as people 'correct' things they've done wrong.

**Comment by alipunjani** [comment]
Hey John, I think your theory is exactly correct. Sorry this wasted so much of your time!

The trouble with md5sum or any other hash is that they depend on every byte in the file, so computing the hash would require reading the entire file from the hard drive every time, so it would basically defeat the purpose of caching. 

The simplest thing to do would be to compare the file modification time stamps between the cache and the original location, but that's not quite foolproof because on high performance systems people sometimes change or disable file time stamping because it causes too many extra reads and writes. I think that's still a good first cut though.

Another option is to write our own hash that only reads some bytes (random selection or say the first 10 bytes of every particle) which would still not be a guarantee, but decent.

**Comment by mbrubake** [comment]
We should definitely check the timestamps and filesize, it's basically free, even if it's not foolproof.  If we want to do a hash check we could make it an option and then hash the first and last 1M (or so).  That should be relatively fast and will catch most issues.

**Comment by johnrubinstein** [comment]
Sound good (no problem about the time spent; was my own fault and learned a few things). I don't think the check has to be completely foolproof.

**Comment by mbrubake** [comment]
Fixed.  Implemented a check of modification time, file size and the first and last MB of the file.  Hopefully reading 2MB will be fast enough that no one will notice, but if it becomes an issue we can either make it optional, randomized or use smaller reads.
