### ISSUE TITLE
Contrast getting inverted for refinement

### ISSUE THREAD

**Issue by mbrubake** [cryoem-uoft/cryosparc-issues#97]
Two different users with two different datasets have seen contrast get inverted for refinement.  In both cases the dataset sign appears to be set correctly and ab initio runs appear to work fine but when switching to refinement, the map gets flipped. @zrip @johnrubinstein @alipunjani Has anyone else seen this kind of behaviour?  There's very little consistency.  One was with a PAR file, another was with a STAR file.  Flipping the datasign doesn't fix things either.

**Comment by johnrubinstein** [comment]
@mbrubake I haven't seen or heard of that happening here. Unless... silly question, but does the refinement succeed or fail? When refinement starts particles are displayed with contrast inverted:
![screen shot 2016-12-14 at 8 46 24 pm](https://cloud.githubusercontent.com/assets/17182155/21208825/91be6e26-c23e-11e6-9045-3b084cc4fc75.png)

**Comment by johnrubinstein** [comment]
Wait, you said the *map* is inverted...

**Comment by johnrubinstein** [comment]
@mbrubake Does everything look okay with the CTF parameters?

**Comment by mbrubake** [comment]
Yeah, the CTF parameters look ok and ab initio works fine. What's even weirder is that if the users specify a different initial map (not one from ab initio) then it seems to work fine.

**Comment by johnrubinstein** [comment]
And it's reproducible when they specify the ab initio map?

**Comment by mbrubake** [comment]
So far, yes. Once I get back I'll try to get the datasets to play with locally. It's really bizarre.

**Comment by johnrubinstein** [comment]
Especially weird if the ab initio map looks somewhat correct. Is any meta data passed from the starting map to the refinement? There must be info about pixel size at least.

**Comment by alipunjani** [comment]
This is probably the strangest bug yet! I can't think of any reason this would happen.. 
The output from abinitio, does it have an ice-density value that's close to zero, or way off?
Very odd. Definitely never seen this before.

**Comment by mbrubake** [comment]
Output from ab initio looks good in both cases. Even the initial map for refinement has its contrast flipped when it's displayed at the beginning.

**Comment by johnrubinstein** [comment]
That's pretty concrete and narrows it down!

**Comment by alipunjani** [comment]
Any symmetry? The only place I can see a connection is during resampling of the abinitio map onto the boxsize of the refinement.. can you try a refinement where you set the boxsize to 64 (same as abinit)

**Comment by mbrubake** [comment]
I'm pretty certain at least one case was C1 but I'm not certain about the other.  I'm in the airport heading back now, but once I'm back I can email them to try to get more info.

**Comment by alipunjani** [comment]
Is the original box size of the particles an odd number maybe?
Ah okay, safe trip home!

**Comment by johnrubinstein** [comment]
Yikes - late flight. Fly safe.

**Comment by mbrubake** [comment]
@johnrubinstein Red eye, not really my favourite but so it goes.

@alipunjani Not sure but a good question to ask.  I'd be surprised if it were an odd number but of course it's not impossible.

**Comment by johnrubinstein** [comment]
I'm not seeing anything weird with the starfile... is there anything strange with the particle stacks? Do you have them?

**Comment by snoreng** [comment]
Hi, I'm one of the people who experienced the flipped contrast. In my case I used C1 symmetry, and the original box size is an even number. The other people I know that experienced the same issue used C2 symmetry on their data set. 

I tried to use a different initial model when I started the refinement to see if that would work, and it seemed to work at first (initial structure showed light particle on dark background), but for the _real space slices iteration000_ the contrast was inverted. 

Sigrid

**Comment by snoreng** [comment]
Also, the particle stacks were created from _relion_stack_create_ , could that cause any problems?

**Comment by johnrubinstein** [comment]
@snoreng are the particles light on dark or dark on light? Is the auto contrast detection accurate by cryoSPARC? (What does it say the particles are?)

**Comment by snoreng** [comment]
@johnrubinstein the particles are light on dark, and cryoSPARC report that the particles are light on dark when it starts the refinement.

**Comment by johnrubinstein** [comment]
@snoreng I'm baffled. If you haven't already, could you share a stack with @mbrubake ? We won't know what your specimen is and Marcus and Ali won't care if its an channel, transporter, ribosome, or whatever.

**Comment by mbrubake** [comment]
@snoreng Thanks for helping us track this down.  If you're able and willing to share the dataset let me know and I'll email you with instructions for uploading it to one of our servers.

**Comment by johnrubinstein** [comment]
@snoreng I notice that different particles from the same micrograph have different defocuses in your starfile. Were CTFs determined per particle (with gCTF or equivalent) or refined (e.g. in Frealign)?

**Comment by mbrubake** [comment]
@johnrubinstein The star file from above is from a different users dataset.  @snoreng would it possible for you to post the PAR/star file for your dataset here?  You can attach it directly to the comment.

**Comment by johnrubinstein** [comment]
@alipunjani @mbrubake Any reason why the CTF changing for every particle could cause problems? I don't think cryosparc would have seen a dataset where that happened before.

**Comment by mbrubake** [comment]
Hmmm, that might just be it!  I think I found a piece of code that might break if every particle has its own CTF parameter.

**Comment by johnrubinstein** [comment]
Cool! On that note I'm going to sleep!

**Comment by snoreng** [comment]
Yes I also used gctf to estimate ctf values so each particle has its own CTF parameters in my data set as well!

**Comment by chesh-ohsu** [comment]
Hi all, I am another user from OHSU, having the inverted particle issue during refinement. I supplemented the star file "160K_localUVA_quisrr2b.star.gz", which refer to particles distributed over 4000 particles stacks. I also tried to make one single particles stacks using "relion_stack_create", and then made a .par file, as in the Frealign convention. Similarly, data formatted in this way worked fine in Ab-Initio but encountered the same inverted particle issue during refinement. As far as I know, this format is consistent with that Wei used in his successful refinement. Unless I am mistaken, I think Wei's data also contained different CTF for each particle, due to local CTF estimation (per particle) by Gctf.

**Comment by chesh-ohsu** [comment]
My name is Shanshuang - I forgot to mention that :)

**Comment by alipunjani** [comment]
I think I figured this one out! There seems to be a bug in our Fourier transform module that only happens when box sizes are _not_ a multiple of 4. For example I see it with a box size of 150 but not 152. It causes the output of ifft to be inverted. The workaround until we figure out how to fix it is to specify a refinement volume size in the parameters that's divisible by 4, rather than using the image size as the volume box size. This is also why the bug doesn't happen in ab-initio reconstruction, because there we always use a box size of 64 by default.

**Comment by mbrubake** [comment]
Wow, good catch!  Does it only happen with ifft or does it happen with fft as well?  If this is the root cause then it has to only occur with ifft, because in ab initio the image size is still the full box size.

@chesh-ohsu @snoreng Can you tell us the box size for your datasets so we can check if this might be the common cause?

**Comment by alipunjani** [comment]
@mbrubake it's also related to the number of dimensions - even number of dimensions works fine, odd number has this problem. i.e it doesn't happen when fft'ing or ifft'ing the images themselves (which is why we don't see the contrast get inverted in the example images at the start of a run). 
With fft'ing or ifft'ing 3D volumes it happens in both directions. But at the beginning of a refinement run, we're usually upsampling a 64^3 initial volume up to the full refinement boxsize (ex. 150^3) and that's where the flip happens - because fft'ing the 64^3 volume is fine but ifft'ing the 150^3 gets inverted.
I'm pretty sure it has something to do with the way I did fftshift via the alternating +1/-1 trick

**Comment by mbrubake** [comment]
Interesting.  Well I guess this makes it a good time to write some unit tests for the fft code and have them run the code through a range of sizes.  I can do that if you want, just let me know.

**Comment by alipunjani** [comment]
That would be awesome if you can. That would also make it much easier to port over to cuFFT.

**Comment by mbrubake** [comment]
Sure, I'll try to write up a few.  I'm almost a little frightened to ask how you found this!

**Comment by alipunjani** [comment]
heh I started having the problem myself today on a testing dataset someone had sent it, with a 150 box size

**Comment by mbrubake** [comment]
I can confirm that I'm seeing this in unit tests even for N=2 with the 3D fft and that the 2D fft seems fine.  I'll finish the unit tests and add in a hack to fix it.

**Comment by mbrubake** [comment]
Ok, unit tested and fixed for now with a bit of a hack.  Not sure why it's necessary but in the name of expedience  it's good enough.  I also added a few sanity checks in case someone passes in an odd-dimensioned volume or image.

**Comment by mbrubake** [comment]
For users the fix for this will show up in the next release.
